---
output:
  pdf_document:
    # citation_package: biblatex
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ../svm-latex-ms.tex
title: "(Work in Progress) Political Donor Polarization: Observing Consumptive Behavior using a Network Approach"
thanks: 
author:
- name: 
affiliation: 
abstract: ""
keywords: "polarization, political donations, network analysis, state politics"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 12pt
spacing: double
bibliography: ../bibliography.bib
biblio-style: apsr
header-includes: \usepackage{graphicx}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(tidyverse)
library(infer)
library(igraph)
```

```{r}
donations <- readRDS("../data/wi_donations.RDA") %>% 
  mutate(source = str_to_lower(str_replace(source, "[[:punct:]]", " ")),
         election_year =  as.character(election_year)) 

donations_n <- donations %>% 
  count() %>% 
  pull()

anon_donations_n <- donations %>% 
  filter(str_detect(source, c("unitemized|anonymous")) == T) %>% 
  count() %>% 
  pull()

donations_2 <- donations %>% 
  filter(str_detect(source, c("unitemized|anonymous")) == F) %>% 
  mutate(zip_5 = str_sub(zip, 1, 5),
         refined_source = refinr::n_gram_merge(refinr::key_collision_merge(source)),
         refined_source_zip = paste0(refined_source," : ",zip_5)) 

filtered_donations <- donations_2 %>% 
  group_by(election_year, refined_source_zip) %>% 
  mutate(source_count = n()) %>% 
  filter(source_count > 1) %>% 
  group_by(election_year, target) %>% 
  mutate(target_count = n()) %>% 
  filter(target_count > 20) %>% 
  ungroup()

polls <- tibble(date = seq.Date(as.Date("2009-01-01"), as.Date("2020-12-31"), 1)) %>% 
  left_join(read_csv("../data/polling_data.csv") %>% 
  mutate(date = lubridate::mdy(date))) 

polls_interpolated <- tibble(date = polls$date,
       neither = polls$neither,
       imputed_neither = imputeTS::na_interpolation(ts(polls$neither), option = "linear"),
       democrat = polls$democrat,
       imputed_democrat = imputeTS::na_interpolation(ts(polls$democrat), option = "linear"),
       republican = polls$republican,
       imputed_republican = imputeTS::na_interpolation(ts(polls$republican), option = "linear")) 
```

```{r}
polls_interpolated %>% 
  filter(date <= "2014-12-12") %>% 
  mutate(neither = neither / 100,
         imputed_neither = imputed_neither / 100) %>% 
  ggplot(aes(x = date)) +
  geom_line(aes(y = imputed_neither), color = "darkgrey")  +
  geom_point(aes(y = neither), color = "black") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 5L), breaks = seq(0, 1, .1)) +
  scale_x_date(breaks = "1 year", date_labels = "%Y") +
  labs(title = "Wisconsin Party Independent/ Neither Party Identification",
       subtitle = "Imputed values",
       caption = "Data: MU Law School Poll & UW-Madison Badger Poll",
       x = "",
       y = "") +
  theme_bw() 
```

```{r}
polls_interpolated %>% 
  filter(date <= "2014-12-12") %>% 
  select(date, contains("imputed")) %>% 
  pivot_longer(cols = c("imputed_neither", "imputed_democrat", "imputed_republican")) %>% 
  group_by(date) %>% 
  mutate(value_fill = value / sum(value)) %>% 
  ggplot(aes(date, value_fill, fill = name)) +
  geom_area() +
  scale_fill_manual(values = c("darkblue", "grey", "darkred"), labels = c("Imputed Democrats", "Imputed Neither/ Independent", "Imputed Republicans")) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 5L), breaks = seq(0, 1, .1)) +
  scale_x_date(breaks = "1 year", date_labels = "%Y") +
  labs(title = "Wisconsin Party Identification 2010-2020",
       subtitle = "Imputed values",
       caption = "Data: MU Law School Poll & UW-Madison Badger Poll",
       x = "",
       y = "") +
  theme_bw() +
  theme(legend.position = "bottom")
```

```{r}
modularity_window <- function(start_date,
                              end_date){

filtered_donations_2 <- filtered_donations %>% 
  filter(date >= start_date & date <= end_date) %>% 
  filter(party != "other") 
  
by_donor <- filtered_donations_2 %>% 
  group_by(refined_source_zip, party) %>% 
  summarize(contribution = sum(contribution)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = party, 
              values_from = contribution) %>% 
  mutate(rep = replace_na(rep, 0),
         dem = replace_na(dem, 0),
         total_contributions = rep + dem,
         per_rep = rep / total_contributions,
         partisanship = scales::rescale(per_rep, to = c(-1, 1)),
         abs_partisanship = abs(partisanship),
         party_bin = case_when(
           per_rep < .25 ~ "democrat",
           per_rep >= .25 & per_rep <= .75 ~ "bipartisan",
           per_rep > .75 ~ "republican"
         ))

nodes_w_party <- by_donor %>% 
  select(refined_source_zip, party_bin) %>% 
  rename(node = refined_source_zip,
         party = party_bin) %>% 
  rbind(donations_2 %>% 
  distinct(target, party) %>% 
    rename(node = target) %>% 
    mutate(party  = case_when(
      party == "rep" ~ "republican",
      party == "dem" ~ "democrat"
    ))) %>% 
  distinct(node, party) %>% 
  mutate(party_num = case_when(
    party == "democrat" ~ 1,
    party == "bipartisan" ~ 2,
    party == "republican" ~ 3
  ))
  
filtered_donations_2 %>%
  select(refined_source_zip, target, contribution) %>% 
  graph_from_data_frame(vertices = nodes_w_party) %>% 
  modularity(nodes_w_party$party_num)
}
```

```{r}
modularity_window(start_date = "2012-01-01",
                  end_date = "2014-12-31")
```

```{r}
tibble(end_date = seq.Date(as.Date("2009-03-01"), as.Date("2014-12-31"), 1)) %>% 
  mutate(start_date )
```

